export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT"
export const FECTCH_ERROR = "FETCH_ERROR"

export const ORDER_START = "ORDER_START"
export const SEND_ORDER = "SEND_ORDER";
export const SEND_FAIL = "SEND_FAIL"
export const ORDER_END = "ORDER_END"


export const FECTCH_ORDERS_START = "FECTCH_ORDERS_START"
export const FECTCH_ORDERS_SUCCESS = "FECTCH_ORDERS_SUCCESS"
export const FECTCH_ORDERS_FAIL = "FECTCH_ORDERS_FAIL"


export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const AUTH_REDIRECT = "AUTH_REDIRECT"
export const SET_ERROR = "SET_ERROR"